[global]
chord_timeout = 65

[ids]
# Laptop keyboard
0001:0001

[main]

# Maps capslock to control
capslock = layer(control)

# Map CoPilot key so that it can be set as Compose in GNOME settings
leftmeta+leftshift+f23 = rightmeta

# Bind the copy/paste keys
# https://mark.stosberg.com/universal-copy-paste/
[alt]
c = copy
v = paste

[control+alt]
v = C-A-v
