#!/bin/sh

# Set DPI so that things render in HiDPI properly
xrandr --dpi 192
export GDK_SCALE=2

# This is done by /etc/X11/xinit/xinitrc.d/50-systemd-user.sh on Arch:
# dbus-update-activation-environment --systemd DISPLAY 

# Make gnome-keyring play nice
# https://wiki.archlinux.org/index.php/GNOME/Keyring#Start_SSH_and_Secrets_components_of_keyring_daemon
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)

# NOTE: Auto-unlock of the keyring requires PAM configuration
# https://wiki.archlinux.org/index.php/GNOME/Keyring#PAM_method
# Add auth optional pam_gnome_keyring.so at the end of the auth section and
# session optional pam_gnome_keyring.so auto_start at the end of the session
# section.
export SSH_AUTH_SOCK

# Polkit agent for virt-manager, etc. (polkit-gnome package on Arch)
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Configure track pad on the fly
# xinput set-prop 16 294 1         # Natural scrolling
# xinput set-prop 16 302 '{0' '1}' # Use 2 or 3 fingers for right and middle click
# xinput set-prop 16 306 0.5       # Increase acceleration

# Configure mouse on the fly
# xinput set-button-map 7 1 2 3 5 4

# Arch Linux
# These are set via /etc/X11/xorg.conf.d/30-touchpad.conf
# Section "InputClass"
#     Identifier "TouchPad"
#     Driver "libinput"
#     MatchIsTouchpad "on"
#     Option "ClickMethod" "clickfinger"
#     Option "NaturalScrolling" "true"
#     Option "AccelSpeed" "0.5"
# EndSection

# FreeBSD
# /usr/local/etc/X11/xorg.conf.d/30-mouse.conf
# http://onethingwell.org/post/8779215052/reverse-scrolling-x11
# Section "InputClass"
#     Identifier "Mouse"
#     MatchDriver "mouse"
#     Option "ZAxisMapping" "5 4"
# EndSection

# Arch
# /etc/X11/xorg.conf.d/30-mouse.conf
# Section "InputClass"
#     Identifier "Mouse"
#     Driver "libinput"
#     MatchIsPointer "on"
#     Option "NaturalScrolling" "true"
# EndSection

# Use menu key as compose key
# https://wiki.archlinux.org/index.php/Xorg/Keyboard_configuration#Configuring_compose_key
setxkbmap -option compose:menu

# Start compositor and WM
picom &
gnome-screensaver &
copyq &
tilda &
emote &
xbanish -t 3 &
