# espanso configuration file

# You can refer to the official documentation:
# https://espanso.org/docs/

# Packages in use
# * all-emojis

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ";+1"
    replace: "Looks good 👍"

  - trigger: ";lorem"
    replace: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

  - trigger: ";shrug"
    replace: "¯\\_(ツ)_/¯"

  # Date and Time
  - trigger: "ddate"
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%d %b %Y" # 17 Aug 2020

  - trigger: "dddate"
    replace: "{{date}}"
    vars:
      - name: date
        type: shell
        params:
          cmd: "date" # Sun 28 Jun 2020 10:53:15 AEST

  - trigger: "ttime"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%r" # 12:34:60 AM

  # Markdown
  - trigger: ";mdl"
    replace: "[$|$]({{clipboard}})" # [|](https://example.com)
    vars:
      - name: "clipboard"
        type: "clipboard"
