words = [
    "allsorts",
    "bmp",
    "bézier",
    "cbdt",
    "cblc",
    "cff",
    "cmap",
    "cpal",
    "dyn",
    "ebdt",
    "fpgm",
    "fvar",
    "gdef",
    "glyf",
    "gpos",
    "gsub",
    "gvar",
    "harfbuzz",
    "hhea",
    "hmtx",
    "maxp",
    "morx",
    "opentype",
    "ppem",
    "sbix",
    "sfnt",
    "ucs",
    "vhea",
    "vmtx",
]
